# Generated by Django 5.1.2 on 2025-01-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(help_text='Enter item name', max_length=200, unique=True, verbose_name='Item Name'),
        ),
    ]
